apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-jamf-cluster
  region: us-east-2
  version: "1.33"

managedNodeGroups:
  - name: my-jamf-nodegroup
    instanceType: t3.micro
    desiredCapacity: 1
    minSize: 1
    maxSize: 3

cloudWatch:
  clusterLogging:
    enableTypes: ["all"]